dataonly:
  image: chrispiemo/rpi-dataonly
redis:
  image: hypriot/rpi-redis:3.0.0
  volumes_from:
   - dataonly
  command: redis-server --appendonly yes
spark:
  build: .
  ports:
   - "4567:4567"
  links:
   - redis:db
  command: target/go-shorty-jar-with-dependencies.jar
